clearviction-devs/clearviction-wa

.github/workflows/nextjs.yml
next.config.js
package.json
pages/about.tsx

- Attemping Nextjs preview using github pages
-   [ ] Bug fix (non-breaking change which fixes an issue)
-   [X] New feature (non-breaking change which adds functionality)
This is an attempt to deploy pull requests to github pages so that reviewers can see changes before they go live.
-   [ ] I have performed a self-review of my own code
-   [ ] I have commented my code, particularly in hard-to-understand areas
-   [ ] I have made corresponding changes to the …

Setup GitHub pages

---

components/DonationForm.tsx

Switched donation widget from donor box to give lively. More ability to style and less fees per donation

Change donation form

---

content/why-vacate.js

-   _[Airtable ticket](https://airtable.com/appfJZShN8K4tcWHU/tblvBIYoi6TLmdRAv/viwOGbkRnFAhe9830/recMwB8ukTn6wPbPs?blocks=hide)_
-   [x] Bug fix (non-breaking change which fixes an issue)
-   [ ] New feature (non-breaking change which adds functionality)
Updates link address.
Fixes # 301
-   [x] I have performed a self-review of my own code
-   [ ] I have commented my code, particularly in hard-to-understand areas
-   [ ] I have made corresponding changes to the documentation (if applicable)
-   [ ] My changes generate no new warnings
-   [ ] I have added tests that prove my fix is effective or that my …

Fix bug 301

---

content/get-started.js

-   _[Airtable ticket](https://airtable.com/appfJZShN8K4tcWHU/tblvBIYoi6TLmdRAv/viwOGbkRnFAhe9830/rec2AnILXjwct64p2?blocks=hide)_
-   [x] Bug fix (non-breaking change which fixes an issue)
-   [ ] New feature (non-breaking change which adds functionality)
Updates the name of the packet link.
Fixes # 303
-   [x] I have performed a self-review of my own code
-   [ ] I have commented my code, particularly in hard-to-understand areas
-   [ ] I have made corresponding changes to the documentation (if applicable)
-   [ ] My changes generate no new warnings
-   [ ] I have added tests that prove my fix is …

Fix bug 303

---

content/why-vacate.js

-   _[Airtable ticket](https://airtable.com/appfJZShN8K4tcWHU/tblvBIYoi6TLmdRAv/viwOGbkRnFAhe9830/recHGJa24o4fb5B5h?blocks=hide)_
-   [x] Bug fix (non-breaking change which fixes an issue)
-   [ ] New feature (non-breaking change which adds functionality)
Update link.
Fixes # 300
-   [x] I have performed a self-review of my own code
-   [ ] I have commented my code, particularly in hard-to-understand areas
-   [ ] I have made corresponding changes to the documentation (if applicable)
-   [ ] My changes generate no new warnings
-   [ ] I have added tests that prove my fix is effective or that my feature …

Fix bug 300

---

.github/pull_request_template.md
components/CalcStepper.tsx
package-lock.json
pages/calculator/[slug].js

-   [S214](https://airtable.com/appfJZShN8K4tcWHU/tblFyv04Eq9CoGA7D/viw9rufLSA7DpxUUK/recwGZZDQggHKRsbM?blocks=hide)
-   [ ] Bug fix (non-breaking change which fixes an issue)
-   [x] New feature (non-breaking change which adds functionality)
Using the existing progress stepper design, implemented the stepper by using the page slugs from Sanity as reference points to break up the calculator into sections. Active styling shows a clear difference between the section the user is currently in, as well as previously completed or not yet done sections. Styling and stepper remain on page refresh, and the stepper is **not** included on the `head` section of the …

Calculator progress stepper

---

pages/calculator/[slug].js
utils/portableTextComponents.js

- [ticket](https://airtable.com/appfJZShN8K4tcWHU/pag0LSYKL2EkzxPkR?2tvjz=recXrHrozZRGWOpwu&dER61=recnFCLGkasAt4EgM&detail=eyJwYWdlSWQiOiJwYWd2OGpFaFU0UmVDb05FcSIsInJvd0lkIjoicmVjd0dLUHRFUnk2Yk9SSUYiLCJzaG93Q29tbWVudHMiOmZhbHNlfQ)
Changes the portable text component object to a named export, which fixed the bug.
Fixes # 308

Fix issue 308: I'm not sure button broken

---

components/ResearchBanner.tsx

3548
- [_[Replace with link to Airtable ticket]_](https://airtable.com/appfJZShN8K4tcWHU/pagxblGyhI5EJIA3v?HjEAY=receMdtgCnYbIMW0v)
- [ X] Link update
Research form link on the homepage was changed from a google doc to airtable 
- [ x] I have performed a self-review of my own code
- [x ] I have commented my code, particularly in hard-to-understand areas
- [ x] I have made corresponding changes to the documentation (if applicable)
- [x ] My changes generate no new warnings
- [ x] I have filled this PR out fully, and cleaned up any extraneous items so that it is clear and easy to understand.

3548 add new at form

---

README.md
components/MailchimpForm.tsx
components/ShareButtons.tsx
package-lock.json
package.json
pages/calculator/[slug].js
pages/get-involved.jsx

- _[[Airtable ticket 3947](https://airtable.com/appfJZShN8K4tcWHU/pagZc4gC1J3AGJCAG?Mif7S=reck64CeDYTr0TNOa)]_
- _[[Airtable ticket 310](https://airtable.com/appfJZShN8K4tcWHU/pag0LSYKL2EkzxPkR?2tvjz=recktIBSfa9R3uzXB&dER61=recVbuNqjmjF38Yfm&detail=eyJwYWdlSWQiOiJwYWd2OGpFaFU0UmVDb05FcSIsInJvd0lkIjoicmVjRTRNUjBIZkxHdVB6YWQiLCJzaG93Q29tbWVudHMiOmZhbHNlfQ)]_
Adds Mailchimp subscription newsletter to the calculator
Adds social media share links to get involved page

Nemo/3947 implement newsletter subscription + 310 add social share

---

components/MailchimpForm.tsx
pages/index.tsx

- _[[Replace with link to Airtable ticket](https://airtable.com/appfJZShN8K4tcWHU/pagxblGyhI5EJIA3v?HjEAY=recXxeYdQVsXeReue)]_
Add MailchimpForm component to the landing page

Added mailchimpForm component to the landing page

---

components/IndividualPageHead.tsx
components/SocialMetaLinks.tsx
content/about.js
content/home.json
content/why-vacate.js
pages/_document.jsx
pages/about.tsx
pages/calculator/[slug].js
pages/contact.tsx
pages/donate.tsx
pages/get-involved.jsx
pages/get-started.tsx
pages/index.tsx
pages/why-vacate.tsx

- _[[Airtable ticket](https://airtable.com/appfJZShN8K4tcWHU/pagxblGyhI5EJIA3v?HjEAY=recoL2x0s6m46yEk7)]_
Creates a new component for the individual page heads, taking in a `title: string` and a `metaContent: string`
Import this component into each page to implement new SEO meta
Updates all H1 elements with new content
Creates a new component for social meta tags and imports into `_document.jsx`

3702 Update title tags, meta descriptions and H1's for all pages of the site

---

README.md
components/IndividualPageHead.tsx
components/MailchimpForm.tsx
components/ShareButtons.tsx
components/SocialMetaLinks.tsx
content/about.js
content/home.json
content/why-vacate.js
package-lock.json
package.json
pages/_document.jsx
pages/about.tsx
pages/calculator/[slug].js
pages/contact.tsx
pages/donate.tsx
pages/get-involved.jsx
pages/get-started.tsx
pages/index.tsx
pages/why-vacate.tsx

Merge staging into main
Making the latest changes live

Merge staging 060423

---

components/GivingTuesdayBanner.tsx
components/MailchimpForm.tsx
components/layout/Header.jsx
package-lock.json
package.json
pages/index.tsx

- _[[Ticket #3946 Redesign Nav bar](https://airtable.com/appfJZShN8K4tcWHU/pagxblGyhI5EJIA3v?HjEAY=recq8M8kAHG9SQZ51)]_
Added Donation Tuesday Banner , vertically aligned the donate button (new color green) and the access calculator button to be on the same line as the NavLogo, and added a navigation bar for all other items. 

3946 new design of nav

---

pages/_app.js

no ticket
Fixes a console error of prop validation failure.
This file will be converted to ts soon and the existing prop validation will be removed anyways, not worth further investigation into fixing.

prop validation failure bandaid until conversion to ts

---

components/NavigationLogo.jsx
components/externalLinks.tsx
components/layout/Header.jsx

- [ X] Bug fix (non-breaking change which fixes an issue)
Update the nav to more closely match the figma. Commented out the Giving Tuesday banner. Increase padding on buttons. Add some class names to elements. Fix logo on large screens
- [ X] I have performed a self-review of my own code
- [ x] I have commented my code, particularly in hard-to-understand areas
- [x ] I have made corresponding changes to the documentation (if applicable)
- [X ] My changes generate no new warnings
- [ X] I have filled this PR out fully, and cleaned up any extraneous items so that it is clear and easy to understand.

Fix nav bar

---

.github/pull_request_template.md

Updating PR template to ask for a screenshot of the Figma file for the ticket.

Include screenshot of Figma in PR template

---

content/why-vacate.js

- _[308 change links https://airtable.com/appfJZShN8K4tcWHU/pag0LSYKL2EkzxPkR?detail=eyJwYWdlSWQiOiJwYWd2OGpFaFU0UmVDb05FcSIsInJvd0lkIjoicmVja0xpUzh4NXhVSWh2TUYiLCJzaG93Q29tbWVudHMiOmZhbHNlfQ&2tvjz=recktIBSfa9R3uzXB]_
Updated the link for  "Post Incarceration Educational Program " > "Pioneer Human Services": to go to  https://pioneerhumanservices.org/job-skills as it provides information on job skills training and its partnerships with community colleges, aligning with the heading indicating post-incarceration educational programs being offered. 

306-change links

---

styles/themes/theme.tsx

- _[[Airtable ticket 4492](https://airtable.com/appfJZShN8K4tcWHU/pagxblGyhI5EJIA3v?HjEAY=recA0tc6YEfjzV0kD)]_
Updates typeography components. First aligns their sizes as outlined in the figma design system sizes, then converts all px to rem. Adds letter spacing and ensures all elements have the correct values per figma. 
Found an neutral object in the palette that doesn't align with anything in the design file so I flagged it for further review. The next steps will be to review the rest of the objects in the theme file.

Align theme file with figma design system

---

public/sitemap.xml

- _[[5649](https://airtable.com/appfJZShN8K4tcWHU/pagxblGyhI5EJIA3v?HjEAY=recYdLQEDhMd1GaxN)]_
Create a sitemap to help search engine crawlers crawl the site more efficiently

5649 create sitemap xml

---

public/robots.txt

- _[[5650](https://airtable.com/appfJZShN8K4tcWHU/pagxblGyhI5EJIA3v?HjEAY=recIP5ImUNymUMsx3)]_
Create a `robots.txt` file to tell search engine crawlers which URLs they can access on the site.

Create robots txt file

---

pages/_app.tsx
pages/_document.tsx
pages/index.tsx

#5259
- _[[Replace with link to Airtable ticket](https://airtable.com/appfJZShN8K4tcWHU/pagxblGyhI5EJIA3v?HjEAY=recm1lmejkNoA4Pto)]_
Updated the index.ts file by removing the G-QNGJLGP9B3 and replace it with GTM-5SPM3GH

5256 gtm link

---

content/get-started.ts

- [Airtable Ticket](https://airtable.com/appfJZShN8K4tcWHU/pagdhiSudV112yoEH?Mif7S=recJs49LTFxtlwvyL&detail=eyJwYWdlSWQiOiJwYWdVUmVIckl0T1gybDlhaiIsInJvd0lkIjoicmVjUDNlN2NQd0VNUENQVEsiLCJzaG93Q29tbWVudHMiOmZhbHNlfQ)
In the Get Started Page, down below to the Financial Aid section, the LFO section was removed. 
The second part, that was completed in Sanity CMS was add a small bunch of words that contain a link that explains what an LFO is. I have reviewed that aspect on [review.clearviction.org](http://review.clearviction.org/) and the page I worked on Sanity CMS is this [this](https://clearviction.sanity.studio/desk/calculatorInfoPage;4a2bdb65-f976-4f06-a594-c8b38c2cf186) 
Fixes # …

Removed LFO section from Financial Aid Forms Content

---

content/get-started.ts

- _https://airtable.com/appfJZShN8K4tcWHU/pagxblGyhI5EJIA3v?HjEAY=recBwqsUiZ945LVFJ_
Minor updates to content on get started page
1. Change "Court Fees" to "Costs Associated with Vacation"
2. Change "Assistance for Pro Se Patrons" to "Representing Yourself in Court"

Update Copy in Step 4 of Get Started Page

---

content/about.ts
content/content.types.ts
content/get-involved.ts
pages/about.tsx
pages/get-involved.tsx

https://airtable.com/appfJZShN8K4tcWHU/pagxblGyhI5EJIA3v?HjEAY=recQqP13kL3q2TWHN
Adds officers to the website.  Our team card format needs to be updated in a separate task.

NEMO-5279/Add officers

---

components/layout/ResearchBanner.tsx

- _[[Airtable ticket 6586](https://airtable.com/appfJZShN8K4tcWHU/pagxblGyhI5EJIA3v?HjEAY=recJvHONcZJX96ypg)]_
Updates text “Help us improve the calculator by participating in research” to “Help improve our services!”
Changes button text from “LEARN MORE” TO “SHARE YOUR EXPERIENCE”
Updates the research form link

Update research banner text and form link

---

components/helper/ShareButtons.tsx
pages/about.tsx

- [[6343](https://airtable.com/appfJZShN8K4tcWHU/pagXdnDYi0tVl4u8R?HjEAY=recJstgb6j88sgOBg)]
- Some className was repetitive and seems not necessary, so im suggesting some name adjusts.
- Some var names were not descritive, in example: `url` 
- Noticed that have some static vars that could be defined outside `ShareButtons` component, helping on not rerender those vars if component rerender.

style: css selectors name share buttons

---

pages/contact.tsx

- _[[Airtable ticket 7968](https://airtable.com/appfJZShN8K4tcWHU/pagXdnDYi0tVl4u8R?HjEAY=reckdXybMbocxtgzU)]_
Created a new formspree account using cvdev@cv
Added the new account info to the doc
Created a new form
Linked info@cv which is a monitored email
Updated contact form with the new formspree url

7968 update formspree

---

content/about.ts
content/contact.ts
content/get-involved.ts
content/get-started.ts
content/home.ts
pages/calculator/[slug].tsx

- 6357
This PR implements the meta data revisions across several pages, per the requests of the Data team. 
Changes were made in accordance with this [google sheet](https://docs.google.com/spreadsheets/d/1XVdwRPePoCCZHyhWQhM02LN02O3U4p-nwxYfxXfiSbg/edit#gid=350003691): 
content/home.ts - updated Title
content/get-started.ts - updated Title and Content
content/get-involved.ts - updated Title
content/about.ts - updated Title and Content
content/contact.ts - updated Title
pages/calculator/[slug].tsx - updated Title
Fixes # 6357
All changes were done to meta data. No changes functional/visual changes.

Nemo 6357/update title tags

---

components/functional/InterceptSurveyForm.tsx
index.d.ts
pages/_app.tsx
pages/_document.tsx

- _[[7981](https://airtable.com/appfJZShN8K4tcWHU/pagXdnDYi0tVl4u8R?HjEAY=rec2nyeY64YmBcPeG)]_
We will use Tally at this moment to implement the intercept survey.
All the logic and storage part is done by Tally, but the trigger on exit intend needed and was implemented.
On Trigger
After opened

feat: add intercept survey

---

components/layout/Footer.tsx
components/layout/HeroBanner.tsx
components/layout/ImageContainer.tsx
components/layout/ResearchBanner.tsx
pages/contact.tsx
pages/get-involved.tsx
pages/get-started.tsx

- [7466](https://airtable.com/appfJZShN8K4tcWHU/pagXdnDYi0tVl4u8R?HjEAY=reci5SKQlviZSjXtR)
- Several images were throwing warnings in the console, the following warnings have been corrected:
- Image with src "/openseattle-logo.png" has either width or height modified, but not the other. If you use CSS to change the size of your image, also include the styles 'width: "auto"' or 'height: "auto"' to maintain the aspect ratio.
- Image with src "illustrations/map.svg" was detected as the Largest Contentful Paint (LCP). Please add the "priority" priority if this image is above the fold. Read more: https://nextjs.org/docs/api-reference/next/image#priority
- Image with src …

Nemo 7466/fix image warnings

---

pages/contact.tsx
styles/themes/theme.tsx

7761
- _[[Replace with link to Airtable ticket](https://airtable.com/appfJZShN8K4tcWHU/pagXdnDYi0tVl4u8R?HjEAY=recylAWWUEgXxOrvi)]_
Double the size of arrow in contactType and made the arrow color darker

7761 2.1.1 contact page drop down menu

---

components/layout/Header.tsx

- [8570](https://airtable.com/appfJZShN8K4tcWHU/pagXdnDYi0tVl4u8R?HjEAY=rec6oO2n5uLKqxzOy)
Update the color of the donate button in [header component](https://www.figma.com/file/icusYj7kJl2xmYkudIZEG4/CV-Current-Design-Files?type=design&node-id=6583-13056&mode=design&t=4XAbsR9Ob3ozVtHq-0) to #2A8613 (palette.success.main) to make sure it passes the WCAG AA level test.
AC: the color of the donate button on the header was updated.

feat: update donate for the WCAG AA level test

---

components/helper/ShareButtons.tsx
components/layout/GetStartedStep.tsx
components/layout/Header.tsx
components/layout/HeroBanner.tsx
components/layout/PaperSection.tsx
content/content.types.ts
content/get-started.ts
content/home.ts
pages/about.tsx
pages/get-involved.tsx
pages/get-started.tsx
pages/index.tsx

- [7765](https://airtable.com/appfJZShN8K4tcWHU/pagXdnDYi0tVl4u8R?HjEAY=recgE4FgLQDMPqabj)
This task involved adding aria-labels to several elements on the website, including:
- Social Media Icons
- Access Calculator Button
- Get Started Button
- Learn More Button
To achieve this, modifications have been made to the respective page, type, content, and layout files in order to incorporate the necessary aria-label data.
No changes to website visuals, the only changes were the additions of aria-labels 

Nemo 7765/consistent identification

---

content/donate.ts
pages/donate.tsx

[9215](https://airtable.com/appfJZShN8K4tcWHU/pagXdnDYi0tVl4u8R?HjEAY=rectm5d3z8PlH10G0)
Eliminate Donorbox button on donate page and as well as donorbox script. 
In the [content file](https://github.com/clearviction-devs/clearviction-wa/blob/main/content/donate.ts), eliminate CTA text and link.

Nemo 9215/eliminate donorbox

---

content/get-involved.ts
pages/donate.tsx

- [6349](https://airtable.com/appfJZShN8K4tcWHU/pagHwvtNNoIIuXqAz?GOswY=recVwH6P2BaS1A1TP)
Add CSS selectors to donate and get involved. The codebase is pretty light on CSS selectors in components that were built as part of the V2 migration to Next.js. Because of this, debugging and finding components in dev-tools can be frustrating and difficult.

Tf 6349/add selectors donate and get involved

---

.github/CODEOWNERS

- [9398](https://airtable.com/appfJZShN8K4tcWHU/pagXdnDYi0tVl4u8R?HjEAY=rec7aKfvtvV9y1jeT)
To streamline the PR process I've added a CODEOWNERS file. Moving forward whenever someone opens a PR to `staging`, ` clearviction-devs/reviewers` will be automatically set as the `Reviewers`
No visual changes to website

Tf 9398/implement code owners

---

package-lock.json
package.json

- [9523](https://airtable.com/appfJZShN8K4tcWHU/pagXdnDYi0tVl4u8R?HjEAY=recKXCOuwMOMdiATh)
Weekly audit of dependency vulnerabilities. We had 1 high level vulnerability that has been resolved.
No visual changes

TF-9523/fix-vulnerabilities

---

.github/workflows/dependency_check.yml

- [9555](https://airtable.com/appfJZShN8K4tcWHU/pagXdnDYi0tVl4u8R?HjEAY=recXPUNsNYLvWJhas)
In order to improve code security, I've implemented a workflow that checks for dependency vulnerabilities. 
- it does this by running the `npm audit` command and pasting the audit report into `.github/workflows/issues/issues- file.txt`
- The workflow searches `.github/workflows/issues/issues-file.txt` using `grep`
- if `grep` does not find `found 0 vulnerabilities` in `.github/workflows/issues/issues-file.txt`, it will comment the audit 
report on the PR
- the workflow will fail the PR if `grep` finds the words `high` or `critical` in the audit report
New files:
- `.github/workflows/issues/issues-file.txt`
- this file should always remain …

TF-9555/implement-dep-check-workflow

---

content/get-involved.ts
pages/get-involved.tsx

- [7322](https://airtable.com/appfJZShN8K4tcWHU/pagXdnDYi0tVl4u8R?HjEAY=recNpeBLvszRcu7Yq)
As Part of the Task Group to improve the Get Involved Page, I've added a FAQ section. I modeled this FAQ section after the FAQ section in the Home page. Content for the FAQ section was taken from this [doc](https://docs.google.com/document/d/1qx6Wsh5LEXPb7X3MkntknGlfaQMveZObdkOkPagikhE/edit?usp=sharing).

Nemo 7322/volunteer faq

---

.github/pull_request_template.md

- _[9231](https://airtable.com/appfJZShN8K4tcWHU/pagXdnDYi0tVl4u8R?HjEAY=recOisFzQw4AXogkZ)_
Adds the new justification form to the PR template. Guidance has been updated in Onboading/Pull requests([9232](https://airtable.com/appfJZShN8K4tcWHU/pagXdnDYi0tVl4u8R?HjEAY=recSpdQ6W9ZxdZ9PS)) and the PR review guide([9233](https://airtable.com/appfJZShN8K4tcWHU/pagXdnDYi0tVl4u8R?HjEAY=recEkChU2cxCEXdRh)).

TF-9231/Add new 3rd party dependency justification form to PR template

---

.github/workflows/cron_job_merge.yml
.github/workflows/scheduled_merge.yml

- _[[10623](https://airtable.com/appfJZShN8K4tcWHU/pagXdnDYi0tVl4u8R?HjEAY=rec2OwfrdhampF6VP)]_
Our cron job was not running every other Tuesday as expected.
This commit is for reset count to start tuesday.

TF 10623/ cron job merge fix schedule

---

.eslintignore
pages/api/revalidate.js
pages/calculator/[slug].tsx
utils/sanity.client.ts
utils/sanity.queries.ts

- _[9929](https://airtable.com/appfJZShN8K4tcWHU/pagXdnDYi0tVl4u8R?HjEAY=reclXMCQ2gA9fKUcv)_
This PR works in tandem with [cv-sanity/PR #6 ](https://github.com/clearviction-devs/clearviction-sanity/pull/6) and should **NOT BE MERGED** until that PR has been merged and changes deployed to Sanity Studio.
- updates `utils/sanity.queries.ts` to allow queries for the new felony pages
- updates `utils/sanity.client.ts` to create usable functions that employ the above Sanity queries
- updates imports and function names in `calculator/[slug].tsx` to accommodate changes to variable names in above 2 files
- removes unused functions in `api/revalidate.js` (that correspond to the deleted schemas from the cv-sanity PR)
This PR sets the stage for the rest of the felony calculator implementation. When …

Tf 9929/integrate felony schemas

---

.github/workflows/3rd-party-check.yml
package-lock.json

- [11418](https://airtable.com/appfJZShN8K4tcWHU/pagXdnDYi0tVl4u8R?HjEAY=recxZyFy2wTHyOEem)
There is an edge case that occurs during some PR's when the vulnerability check workflow detects vulnerabilities. When the dev opening the PR resolves the dependency vulnerabilities, the 3rd party dependency workflow will post the dependency justification form because it detects changes in the package-lock.json file. This PR fixes that behavior.
Please reference [pr162](https://github.com/clearviction-devs/clearviction-wa/pull/162)
Commit [7fa77bf](https://github.com/clearviction-devs/clearviction-wa/pull/162/commits/7fa77bf9228c30979722e23bf94ebc9b4defcf13) confirms that the workflow will not fire when just the `package-lock.json` has been …

Tf 11418/refactor third party dep workflow

---

.github/dependabot.yml

- _[11428](https://airtable.com/appfJZShN8K4tcWHU/pagXdnDYi0tVl4u8R?HjEAY=recGIctemkQoPWD7R)_
Adds a dependabot configuration file to the `.github` directory, which will enable it to create pull requests for package updates.
No code changes.

Create dependabot.yml to enable package update pull requests

---

.github/workflows/3rd-party-check.yml

Add conditionals to check for dependabot
- [11493](https://airtable.com/appfJZShN8K4tcWHU/pagXdnDYi0tVl4u8R?HjEAY=recT4bCInAsrEw0TO)
The 3rd Part Check workflow unnecessarily posts the third party justification form on PR's opened by dependabot.
This PR resolves this issue by updating the conditional in the `Post Comment` step of the workflow. The workflow will now check to see if the PR is opened by `dependabot[bot]` and `dependabot-preview[bot]` the two potential login values for dependabot.  
N/A
_Please delete any options that are …

TF-11493/dependabot-3rd-party-workflow-fix

---

components/functional/usePostRequest.tsx

- [11494](https://airtable.com/appfJZShN8K4tcWHU/pagXdnDYi0tVl4u8R?HjEAY=recn4iNAVpvRCXFk7)
This PR improves the typing of `components/functional/usePostRequest.tsx` by doing the following:
- Creating an TReqBody generic type
- Setting url parameter type to string
- Setting requestBody param type to TReqBody
- Setting makeRequest return type to Promise<void>
N/A

TF-11494/post-request-typing

---

package-lock.json
package.json

- _[11537](https://airtable.com/appfJZShN8K4tcWHU/pagXdnDYi0tVl4u8R?HjEAY=recbiUHTyMkNkm3Wj)_
As part of enabling dependabot, I reviewed the entire contents of the `package.json` and found quite a few that don't seem to be used anywhere. Please review my work carefully, changes like this can have hidden consequences. I manually tested as many things as I could find.

TF-11537 Audit package.json

---

pages/get-involved.tsx

- _[[11738](https://airtable.com/appfJZShN8K4tcWHU/pagGjwSExQEbHC3z9?3psIY=recsy9LrUGbHwzTiu&detail=eyJwYWdlSWQiOiJwYWdVUmVIckl0T1gybDlhaiIsInJvd0lkIjoicmVjZGk0eTJiQmJHQXVIb3MiLCJzaG93Q29tbWVudHMiOmZhbHNlfQ)]_
The "Get Involved" section on our website currently has inconsistent padding due to the testimonial section x axis overflow, leading to a cluttered appearance. This task involves adjusting the padding to ensure visual harmony and alignment with our design standards.

website 11738/Fix get involved overflow

---

content/get-involved.ts

[Link to AirTable Ticket 11883 
](https://airtable.com/appfJZShN8K4tcWHU/pagGjwSExQEbHC3z9?detail=eyJwYWdlSWQiOiJwYWdVUmVIckl0T1gybDlhaiIsInJvd0lkIjoicmVjeE9Gak9NdWd4NVRNTG8iLCJzaG93Q29tbWVudHMiOmZhbHNlfQ)
There was a typo on the 'Get Involved' page, specifically in the 'Perfect Fit' section. 
Fixes # 11883

11883 fix typo on get-involved page

---

components/layout/Header.tsx

[[7444]](https://airtable.com/appfJZShN8K4tcWHU/pagGjwSExQEbHC3z9?3psIY=recsy9LrUGbHwzTiu&detail=eyJwYWdlSWQiOiJwYWdVUmVIckl0T1gybDlhaiIsInJvd0lkIjoicmVjYzU1aEo4alREOFhZakwiLCJzaG93Q29tbWVudHMiOmZhbHNlfQ)
Problem:  Currently the Mobile menu drawer has no visible exit (some users may not understand to tap away from the menu to close it).  It is also inconsistent with the desktop global navigation because it doesn’t have the “calculator access” CTA or the “donate” CTA - only additional nav items without hierarchy
Goal:  Make the hamburger menu of the mobile and tablet version more usable and consistent with the desktop version more clear.

Website 7444/implement updated mobile nav design

---

.github/workflows/cron_job_merge.yml

- [12062](https://airtable.com/appfJZShN8K4tcWHU/pagXdnDYi0tVl4u8R?HjEAY=reclXiwHg79LxAVtg)
Our cron job ran twice, we need to investigate and fix this.
The "problem" seems to be related to leap day and frequency on days. [some explanation](https://en.wikipedia.org/wiki/Cron#:~:text=Note%20that%20frequencies,mere%20pattern%2Dmatcher)

fix: schedule cron to run on day 1 and 15 each month

---

cypress/e2e/access-calculator.cy.ts
cypress/e2e/misdemeanor/fishing/eligible-path.cy.ts
cypress/e2e/misdemeanor/fishing/ineligible-choises.cy.ts

- _[12261](https://airtable.com/appfJZShN8K4tcWHU/pagHwvtNNoIIuXqAz?GOswY=recFBOldrq8UAIPkh)_
This PR use cypress to test Fishing violation paths, either eligible and ineligible.
_Include relevant screenshots_

test: misdemeanor fishing violation tests

---

.github/workflows/pr-testing.yml

- _[12526](https://airtable.com/appfJZShN8K4tcWHU/pagXdnDYi0tVl4u8R?HjEAY=recckpr4rD3iM06Jx)_
We are having some problems with `actions/cache` because it uses node 16, and our pipeline environment uses node 20.

chore(ci): update actions cache to v4

---

cypress/e2e/misdemeanor/marijuana/eligible-path.cy.ts
cypress/e2e/misdemeanor/marijuana/pages/m-offense-mari-1-cont.cy.ts

- _[12261](https://airtable.com/appfJZShN8K4tcWHU/pagXdnDYi0tVl4u8R?HjEAY=recOqZixUOFeVcMoC)_
Possession of Marijuana is part of misdeameanor path.
Need to create tests that check the path to elegible and all individual middle pages to check other behaviors.

TF-12261/ test misdemeanor possession of marijuana

---

.github/workflows/README.md

Removes outdated and unused documentation from the workflows readme.

Remove old workflows from CI documentation

---

cypress/e2e/felony/class-b/no-pros/terms-of-offense/pages/f-terms-classb-1-cont.cy.ts
cypress/e2e/felony/class-b/no-pros/terms-of-offense/pages/f-terms-classb-1-main.cy.ts
cypress/e2e/felony/class-b/no-pros/terms-of-offense/pages/f-terms-classb-eligible.cy.ts
cypress/e2e/felony/class-b/no-pros/terms-of-offense/pages/f-terms-classb-ineligible.cy.ts
cypress/e2e/utils/testEligiblePage.ts
cypress/e2e/utils/testEligibleWithLFOPage.ts

[Airtable Ticket #12810
](https://airtable.com/appfJZShN8K4tcWHU/pagHwvtNNoIIuXqAz?GOswY=recFBOldrq8UAIPkh&detail=eyJwYWdlSWQiOiJwYWdxbjhheFdqS0JvVVYwYiIsInJvd0lkIjoicmVjQzdnaEpLMFVoeVNUdnQiLCJzaG93Q29tbWVudHMiOmZhbHNlfQ) 
- Testing
This pull request implements end-to-end testing for the Felony Calculator's Class B (No Pros) branch, specifically focusing on the third section: Terms of Offense. The test suite structure is organized within the `e2e/felony/class-b/no-pros/terms-of-offense/pages` directory. You can find the link to the Figma File [here](https://www.figma.com/file/icusYj7kJl2xmYkudIZEG4/CV-Current-Design-Files?type=design&node-id=19603-69520&mode=design&t=yWhSsbRdtKnTE7Qz-4).
**1. Test Structure**:
- **Directory Organization**: Test files are structured within the …

Tf 12810/Implement End-to-End Testing for Felony Calculator Class B (No Pros) Branch Third Section

---

components/functional/DisclaimerBanner.tsx
components/layout/CarouselBuilder.tsx
components/layout/Header.tsx
components/layout/HeroBanner.tsx
components/layout/PlayCard.tsx
pages/index.tsx

fix home page issues

---

components/calculator/CalcHeader.tsx

Resolves low priority console warnings when going through the calculator.

Resolve console warnings

---

components/layout/DisclaimerBanner.tsx

Adjusts the alignment of the disclaimer banner text by removing the width settings on different screen sizes which were not correctly aligned with the header buttons, and uses a center alignment for all screens. Sets the last updated date to today, 11/20/24.

Update disclaimer banner date
