components/externalLinks.tsx
content/about.js
package-lock.json
package.json
pages/get-started.tsx
pages/why-vacate.tsx
styles/themes/theme.tsx

Removes @next/font dependency and changes import to built in next/font, as was recommended by the warning in the console on startup.
Removes an extra grid spacing prop that is not allowed to be used without specifying the container prop on the same component, which fixes the warning and doesn't appear to make any difference either.
Adds rel="noopener noreferrer" to links in externalLinks function for security purposes. This does not, however, fix the warning that this function started displaying in the browser console.

Fix warnings

---

content/why-vacate.js

-   [Update the content on the "Why Vacate" page](https://airtable.com/appfJZShN8K4tcWHU/pagZc4gC1J3AGJCAG?OjYm8=b%3AeyI0emRmdyI6W1s2LFsicmVjQjJrN1pMczZOb215VlkiXV1dfQ&Mif7S=recZAUdl3bNO7nCVJ&detail=eyJwYWdlSWQiOiJwYWcwSmF6REhuQURDT3VQbyIsInJvd0lkIjoicmVjWmUxOGxZRWRrczlVNDcifQ)
-   [ ] Bug fix (non-breaking change which fixes an issue)
-   [ ] New feature (non-breaking change which adds functionality)
-   [X] Other
Update _Why Vacate_ page content JSON file to make tone of page less negative and more positive. Using content team's [recommended changes](https://docs.google.com/document/d/1mMYth9kswBpzxzo07c6LEEDczetjn8ulIjUPMxZxrB0/edit), phrases on the …

Updated 'Why vacate' content

---

components/SocialMetaLinks.jsx

After looking at the meta tags a little bit more, maybe they were somehow working like this in the old repo and are not valid with next..? Anyways, I added `https:` to the start of all the urls, and I updated the `og:url` from `/givingtuesday` to `/donate`. After that maybe we can see if Tomas can test posting using the `staging.clearviction.org` url. Not sure if this is the fix but I have verified everything else on the entire repo is the correct icons and images.
It still doesn't make sense where the Open Seattle and Democracy Lab stuff is coming from though. We have their images in the repo, but the only place they are used is in the footer.

add https: to meta urls, update og:url to /donate

---

components/AccordionBuilder.tsx

- _https://airtable.com/appfJZShN8K4tcWHU/pag0LSYKL2EkzxPkR?2tvjz=rec0iQeSDMiCBgfr7&detail=eyJwYWdlSWQiOiJwYWd2OGpFaFU0UmVDb05FcSIsInJvd0lkIjoicmVjczlaSTBUYldXTFUwOXIiLCJzaG93Q29tbWVudHMiOmZhbHNlfQ_
The spacing between links made it difficult to tell what is a link vs a line break

299-Link Spacing

---

content/why-vacate.ts

- _[[Issue ticket 340](https://airtable.com/appfJZShN8K4tcWHU/paghvE9diS74Z0Csc?c7fi2=recVlR2mpPtILo60Y)]_
On the website, under "why vacate", under "housing", we state: "A background check is an obstacle for people with a conviction and it can prevent access to certain opportunities. Here are the main challenges background checks present to those seeking AN EDUCATION".
Changes "AN EDUCATION" to "HOUSING" since we mean to say housing since we share obstacles about housing. Screenshots are provided to demonstrate.

Wrong word used on why vacate page

---

components/functional/CalcStepper.tsx

- _[[Airtable ticket 6105](https://airtable.com/appfJZShN8K4tcWHU/pagxblGyhI5EJIA3v?HjEAY=recgZge2MTw3NhFZo)]_
CalcStepper component on mobile screens was cut off because it was displaying the title off all 3 steps which was too much text, too long. I adjusted the stepper to check if active step matches the current step's label, and only then to display the title of the step section. I tried to duplicate as little as possibly without nesting ternaries or if statements inside the JSX, both of which aren't allowed.
Also, for some reason (thinking the rendering), the useMediaQuery does work on the calculator!
Fixes # 345
The Figma doesn't exactly match our current stepper, but I did just spend another hour trying to override styles on different parts of the …

Fix bug 345

---

pages/_app.tsx
pages/_document.tsx

Updates the recently merged meta tag PR. There was one piece of meta (viewport) in `_app.tsx` which we moved to document to keep everything clean, but that is apparently not allowed with Next, so this puts it back.

fix: move viewport meta tag back to app

---

pages/get-involved.tsx

Adds the props to the original use of ShareButtons component, that were recently added with the extension of the component. This was causing a build error in AWS.

fix: props on share button component

---

pages/get-involved.tsx

https://airtable.com/appfJZShN8K4tcWHU/pagxblGyhI5EJIA3v?HjEAY=recv3HaBRSb5GQw6Y
This commit addresses layout and responsiveness issues on the 'get-involved' page. The "waysToParticipate" grid was decentralized, leading to problems on mobile devices and an overflow issue along the x-axis. The header layout was disrupted as a result.

Nemo 6244/fix waystoparticipate grid

---

components/layout/Footer.tsx
content/footer.ts

- https://airtable.com/appfJZShN8K4tcWHU/pagxblGyhI5EJIA3v?HjEAY=rec9voG6hM6BS7Io9
Implements new footer design. Adds address and more information to the footer, and changes the alignments.
The implementation has two differences with the design in mobile view mode: 
1. The navItems are a bit farther for easier touching. 
2. The font of the navItems remains subtitle2 in mobile mode in order to have a difference from its heading.

Nemo 5727/update footer with address and less links

---

components/layout/Header.tsx

https://airtable.com/appfJZShN8K4tcWHU/paghvE9diS74Z0Csc?c7fi2=recHohD7PXFrHeFly
Fixed the CSS overflow-x issue occurring in the header when the screen width fell within the range of 900px to 996px. Adjusted the styling to ensure proper display and prevent horizontal scrolling.
Fixes # 354

fix: resolve navbar overflow-x issue in certain screen sizes

---

pages/_document.tsx

In order to get our website rescraped by Google, without adding DNS records to do so, we can use this verification meta tag. I made this PR against main so that I can complete the rest of the steps on the Google search console.

Add meta tag for google site verification

---

components/layout/Footer.tsx
components/layout/ResearchBanner.tsx

- _[[Airtable ticket 6562](https://airtable.com/appfJZShN8K4tcWHU/pagxblGyhI5EJIA3v?HjEAY=recHTeru3ajdF9FCw)]_
The image in the research banner as well as the open seattle logo in the footer had warnings in the console about the height and width being set improperly, basically setting one without the other, and this PR resolves both. In the research banner this adds a `height: auto` to the style prop, and in the footer, remove `useImageDimensions`, since the component is also simultaneously setting a new width, which was contradictory.

6562 Fix homepage image bugs

---

pages/contact.tsx

- _[Airtable ticket 6362 4.1.3 status Messages](https://airtable.com/appfJZShN8K4tcWHU/pagXdnDYi0tVl4u8R?HjEAY=recqjdooelGHdMfPK)_
Update the status message on the contact form. The form should be accessible when tabbing through the form and the screen reader should read the inputs, and error messages inline as they occur. 

NEMO-6362 error messages and validation in contact form

---

components/layout/Footer.tsx

- _[[6345](https://airtable.com/appfJZShN8K4tcWHU/pagXdnDYi0tVl4u8R?HjEAY=recIWN89Ap0OmZSmx)]_
- Some Footer components have either not declarative className or no className. Because of that debugging can sometimes be difficult.
- Footer has some repetitive sections that maybe could have a custom component (`FooterSection`).
- We are using the same full address in two different places, so would be interesting if we implement something (`FullAddress`) and use that where we need inside Footer. (Single Source of Truth)
- Footer is using `Hidden` MUI component, which is deprecated in MUI v5 ([Hidden](https://mui.com/material-ui/react-hidden/)), so a migration may be a good option.

style: css selectors name on footer component

---

components/layout/Footer.tsx
components/layout/HeroBanner.tsx
components/layout/ResearchBanner.tsx

- [[6344](https://airtable.com/appfJZShN8K4tcWHU/pagXdnDYi0tVl4u8R?HjEAY=recOljFtIzjb5eZR1)]
Hero Banner and Research banner are light on Css selectors, which makes debugging hard.
- Added CSS selectores on Hero Banner  and Research Banner
- Adjusted Footer component on `Welcome` section, because it was not how style was expected
- Align arrows on Footer Explore grid.

css selectors hero and research banner

---

components/functional/CustomScroll.tsx
components/layout/Header.tsx
pages/about.tsx
pages/get-started.tsx
pages/index.tsx
pages/why-vacate.tsx

[7358](https://airtable.com/appfJZShN8K4tcWHU/pagXdnDYi0tVl4u8R?HjEAY=rec0agbQRpUgFN61O)
All href links on all pages are not scrolling properly due to our navbar's size (200px tall). One possible solution is to inspect these href components and make them scroll to a position -200 pixels, so that they can account for the navbar's size. I've added images of the scrolling final position before and after the changes.

Nemo 7358/fix href scroll

---

pages/about.tsx
pages/contact.tsx

- [6347](https://airtable.com/appfJZShN8K4tcWHU/pagXdnDYi0tVl4u8R?HjEAY=rec9jzRRavJ6ZUHQi)
I think our about and contact pages were pretty good in terms of CSS selectors. The additional id's I added in either help differentiate container elements on pages, or in the case of some buttons, add clarity to elements that are being rendered through content data. The contact form already has a significant amount of selectors, so I refrained from adding any there.
I went with id's instead of classnames because many of the materialUI elements already have many classnames. 
No relevant screenshots as the only changes were adding additional id values to elements

Tf 6347/add css selectors to about contact

---

pages/get-started.tsx
pages/why-vacate.tsx

- [6348](https://airtable.com/appfJZShN8K4tcWHU/pagXdnDYi0tVl4u8R?HjEAY=recO81WnsPRkZf4Y8)
Add CSS selectors to get started, why vacate. The codebase is pretty light on CSS selectors in components that were built as part of the V2 migration to Next.js. Because of this, debugging and finding components in dev-tools can be frustrating and difficult.

Tf 6348/add css selectors get started and why vacate

---

components/layout/Header.tsx

- [7768](https://airtable.com/appfJZShN8K4tcWHU/pagXdnDYi0tVl4u8R?HjEAY=rec8uCGbxDHmnbohQ)
When using a voice reader, sometimes the Reader reads instances of `ABOUT US` incorrectly. The only instance I found of this is in the NavBar because the Button text is all caps. I added an aria-label to correct this issue. Testing to make sure the voice reader read it correctly was done using [ScreenReader](https://chrome.google.com/webstore/detail/screen-reader/kgejglhpjiefppelpmljglcjbhoiplfn/related) and Chrome, as well as the default Mac Voice Reader and Safari.
No changes to website visuals, only additional aria-labels

Add aria-label to nav buttons using lower case names

---

content/get-started.ts
content/why-vacate.ts

- [9400](https://airtable.com/appfJZShN8K4tcWHU/pagXdnDYi0tVl4u8R?HjEAY=recM3AjfNKLtk2vb7)
The in-page navigation buttons for the `why-vacate` and `get-started` were not properly navigating to the correct page sections. I have corrected this issue.
No visual changes

Tf 9400/fix get started buttons

---

.github/workflows/scheduled_merge.yml

- [8784](https://airtable.com/appfJZShN8K4tcWHU/pagXdnDYi0tVl4u8R?HjEAY=rec1pUwPFHLipqUm1)
Add a new workflow that handle `staging into main` process from TF team every other week.
This workflow has some jobs before merging to do some basics verification on code to be merged.
If something fail, a new issue is created to inform that something need to be done.
`IMPORTANT NOTE:` We need to create some env before merge this

TF-8784/Add workflow cron job to merge staging into main every other week

---

.github/workflows/README.md

- _[10264](https://airtable.com/appfJZShN8K4tcWHU/pagXdnDYi0tVl4u8R?HjEAY=recDL0qRV0V6OWhR9)_
Moves our finalized CICD documentation into the `.github/workflows` folder as a `README.md`, and deletes the word docs copy so that this is the single SOT. [View the file](https://github.com/clearviction-devs/clearviction-wa/tree/TF-10264/cicd-to-readme/.github/workflows)

Add CICD workflow doc to workflows folder as readme

---

.github/workflows/3rd-party-check.yml
.github/workflows/README.md

- [10293](https://airtable.com/appfJZShN8K4tcWHU/pagXdnDYi0tVl4u8R?HjEAY=rec6E6oA7jDcAh5sS)
- Currently our `New 3rd Party Dependency Check` workflow has a bug where it keeps commenting the justification form every time a new commit is pushed to a PR that includes changes to the `package.json` or `package-lock.json` files. 
- I have resolved this issue in the following ways:
-  I have added a step that checks the comment history of the PR and looks for a comment with `` tag. This will determine whether the form is posted as a comment on the PR
- In the post comment step, I have refactored the conditional to check if `comment_already_posted` is `false`
- the `Post Comment` step also now adds the `DependencyCheckTag` to the comment …

Tf 10293/refactor 3rd party workflow

---

pages/index.tsx

- [6350](https://airtable.com/appfJZShN8K4tcWHU/pagXdnDYi0tVl4u8R?HjEAY=recmZXm8MZXok1Xt6)
Add CSS selectors to index. The codebase is pretty light on CSS selectors in components that were built as part of the V2 migration to Next.js. Because of this, debugging and finding components in dev-tools can be frustrating and difficult.
NA

Add CSS Selectors to index

---

.github/pull_request_template.md

- _[10668](https://airtable.com/appfJZShN8K4tcWHU/pagXdnDYi0tVl4u8R?HjEAY=recapYBo2MiP1aVbs)_
Adds the PR review guide checklist to the PR template so that contributors can self-review according to the terms we review them on, hopefully decreasing further changes needing to be requested.

Add PR checklist from docs to PR template

---

.github/dependabot.yml

- _[11842](https://airtable.com/appfJZShN8K4tcWHU/pagXdnDYi0tVl4u8R?HjEAY=rectX5fdhaDRHmKSd)_
Updates the `dependabot.yml` with further consideration of our actual needs from dependabot. Using groups, dependabot will open one pull request on behalf of all dependencies in that group. I separated them into prod dependencies and dev dependencies, and allow for only major and minor update types, omitting patch. I further ignored all major version updates specifically for next, since we want to control when that happens separately.

Use groups to contain dependabot updates into group PRs

---

.github/dependabot.yml

- _[11842](https://airtable.com/appfJZShN8K4tcWHU/pagXdnDYi0tVl4u8R?HjEAY=rectX5fdhaDRHmKSd)_
Updates the `dependabot.yml` again, adding the patches to the group PRs. Previously I had meant to just not include the patch updates but when an update it not caught by a group it just opens it's own PR which is not what I had intended. Since the PR now includes all of the updates together I think it is okay to leave them in.

Include patch updates in group update PR, add next-sanity to ignore

---

.github/dependabot.yml

- _[12100](https://airtable.com/appfJZShN8K4tcWHU/pagXdnDYi0tVl4u8R?HjEAY=recrj7x6p4nQGR1Th)_
Dependencies matching `@mui/*` with major version updates are ignored by dependabot version updates.

TF 12100/add major version updates of MUI to dependabot ignore

---

.vscode/settings.json

- _[12221](https://airtable.com/appfJZShN8K4tcWHU/pagXdnDYi0tVl4u8R?HjEAY=recAHApGXOxRmKg7n)_
The [Sept 2023 release of VSCode](https://code.visualstudio.com/updates/v1_85#_code-actions-on-save-and-auto) updated the syntax for the `source.fixAll.eslint` key in our `settings.json` file. This PR updates the file to use the new syntax.

update to new syntax and value for editor setting

---

components/calculator/CTAContainers.tsx
pages/calculator/[slug].tsx
utils/calculator.props.ts
utils/sanity.queries.ts

- _[12582](https://airtable.com/appfJZShN8K4tcWHU/pagXdnDYi0tVl4u8R?HjEAY=rec0OQP5EOkol7cgS)_
When the calculator was live with only the misdemeanor branch, we had a "undetermined eligibility" boolean flag in sanity, as well as a feedback form url for folks who landed on this page, when clicking that their conviction was NOT a misdemeanor. Now that the felony calculator is live we no longer need this.
**NOTE:** the tests pass locally, but not here on the PR. This is because the PR is using an old Sanity build and locally we are using the most recent sanity changes. 
This PR corresponds to [cv-devs/cv-sanity PR #45](https://github.com/clearviction-devs/clearviction-sanity/pull/45)
Please self review your work before requesting further review. _Wait until you reach the next screen to check …

remove undetermined feedback url and isDetermined field from page

---

.github/dependabot.yml

The new major version update of `eslint` to `v9.0.0` brings many breaking changes, according to [the docs](https://eslint.org/blog/2024/04/eslint-v9.0.0-released/). This will require a migration and some changes on our part, but we also need to wait for `eslint-airbnb-config` to make the update to v9 as well because right now the conflicting peer dependencies are causing a failure in the install step.
This adds `eslint` to the dependabot ignore array so that we can do this on our own time.

Add eslint major version update to dependabot ignore

---

pages/_document.tsx

When cleaning out our AWS account, I had deleted all of the unused buckets. It seems that we were using one single image in a bucket for our meta tag `og:image`, which I replaced with the equivalent version that already exists in the repo, on our homepage.

replace meta og:image with copy in repo vs AWS bucket

---

components/layout/Header.tsx
content/content.types.ts
content/navItems.ts
pages/get-started/determine-your-eligibility.tsx
pages/get-started/file-with-the-court.tsx
pages/get-started/gather-your-documentation.tsx
pages/get-started/index.tsx
pages/why-vacate/educational-benefits.tsx
pages/why-vacate/employment-benefits.tsx
pages/why-vacate/housing-benefits.tsx
pages/why-vacate/index.tsx

Updates the file and folder structure to accommodate the new dropdown and subpages for why-vacate and get-started. There is now a new folder for each in the pages directory, and the index.tsx file in each is the formerly /why-vacate and /get-started pages. This should allow for everyone to easily continue work on the rest of these pages.

update file and folder structure for why-vacate and get-started subpages

---

components/calculator/PopupContainers.tsx
components/calculator/QandAContainer.tsx
components/calculator/RCWLinkInfo.tsx
components/functional/DisclaimerBanner.tsx
components/helper/CustomButtons.tsx
components/layout/Header.tsx
components/layout/HeroBanner.tsx
cypress/e2e/access-calculator.cy.ts
pages/_app.tsx
pages/calculator/[slug].tsx

Completes the following tasks in Trello:

calculator & home page fixes

---

utils/portableTextComponents.tsx

Changes to content in Sanity and styling of block content to add margins to body2 text.

add bottom margin to body2 elements, use h6 in sanity to style lists as body2 without margin

---

components/calculator/CalcHeader.tsx

Previously, the progress bar stayed outdated whenever the user clicks on the browser's back button. I resolved the issue by ensuring that the CalcHeader component is remounted whenever navigation changes using useEffect and useRouter. 
Fixes Trello Ticket- link [here](https://trello.com/c/QeUDNzm9/20-fix-progress-bar) 
Next.js Doc on Resetting State after Navigation - link [here](https://nextjs.org/docs/pages/api-reference/functions/use-router#resetting-state-after-navigation)

Reset state after when using the browser's back button

---

components/layout/DisclaimerBanner.tsx

Previously, the disclaimer icon would be slightly misaligned. I addressed this by wrapping the icon in a parent div and applied flex styling so that the icon would always be centered vertically.

Align disclaimer icon

---

components/layout/AccordionBuilder.tsx

Trello ticket [here](https://trello.com/c/vDvyLRif/76-fix-faq-list-item-spacing)
The list items in the `AccordionBuilder` component did not have any spacing. According to the figma I found a 10px gap when selecting the container so I added that as bottom margin to each list item.

fix list item spacing

---

components/CustomButtons.tsx
components/layout/Header.tsx
content/content.types.ts
content/navItems.ts
styles/themes/theme.tsx

Nav items in header were unaligned, notably the buttons. Some of the changes I made include:
1. **Removed `minWidth` MUI button override in theme:** It was causing layout issues as one of the buttons had a smaller width requirement.
2. **Added `item.width` to `NavItem` interface:** To implement precise button widths according to the Figma design
3. **Added responsive padding at 1440px:** Introduced a breakpoint to adjust padding on wider screens.
Trello ticket [link](https://trello.com/c/d6FXq76T/45-nav-items-slightly-unaligned-low-priority)  
Figma [link](https://www.figma.com/design/NzfRmePoBPp4yrxTMrNRz1/CV-Website-Update.-4.2024?node-id=2509-34266&t=aNtZnV7WaUaHbKQj-4)

Align nav items

---

components/CustomButtons.tsx
components/layout/Header.tsx

Hamburger menu did not fully match Figma. Updates include:
- Ensuring the menu covers 72% of the screen when opened
- Adding a dark blue hover background for improved accessibility
- Adjusting the spacing for proper alignment
- Updating button styles
Trello ticket [link](https://trello.com/c/5kvnaoL4/82-hamburger-menu-styles-do-not-match-figma-designs)  
Figma [link 1](https://www.figma.com/design/NzfRmePoBPp4yrxTMrNRz1/CV-Website-Update.-4.2024?node-id=1134-39595&node-type=frame&t=pkcvGwZS7JhQNOvR-0)
Figma [link 2](https://www.figma.com/design/NzfRmePoBPp4yrxTMrNRz1/CV-Website-Update.-4.2024?node-id=578-7808&node-type=instance&t=avzUTiwbVxw9MgNK-0)

Style hamburger menu

---

pages/get-started/determine-your-eligibility.tsx

Trello ticket [here](https://trello.com/c/PZ5dLxG9/78-fix-section-margins)
The padding of the container that the get started pages use gets its padding from the figma, but it is just a base to start from and as all of the containers in the figma tend to vary in their top and bottom padding, many of the containers require some modification. Originally I created these containers because I was having issues with the SectionContainer component taking in any sx props and overriding everything which caused lots of unwanted behavior. Later after using these new containers, during a review of the components I realized that the SectionContainer was missing the spread in of the sx props below its own sx props, which ended up resolving the original issue and allowing me to fix some things on the …

adjust flex properties of CTA box to fix item misalignment

---

components/calculator/CalcHeader.tsx

Previously we had refactored a block of if statements checking conditions for the progress bar into a switch statement, which was cleaner, however it had some unintended side effects. The switch statement was catching the pathname including 'classcpro' or 'classbpro' to set the progress bar to 2 sections instead of 3 on felony prostitution paths, but then it was breaking and never catching the pathname including 'eligible' or 'ineligible' to set the progress bar on end pages correctly.
Since the time of the change to the switch statement, some other parts of the switch statement were removed, and refactoring this into 2 if statements instead of the 4 or more that it previously was, did not revert us back to very messy code. Using if statements, we are able to catch both conditions on the …

refactor progress bar switch

---

components/layout/CarouselBuilder.tsx
pages/get-started/file-with-the-court.tsx

This adjusts the 5 card carousel on `get-started/file-with-the-court`. Previously the carousel cut off at `936px` and only showed a max of 3 cards, leaving it easy to miss the last 2 cards on the page. According to the figma, the carousel would not  break but rather as the screen size expanded the cards would spread out across the page. The issue here is that once we pass the medium breakpoint (`1000px`) we move from specific `x` padding to `auto` `x` margin, and according to the figma we only wanted the left side to have the margin. In this PR, it slightly differs from the figma in that the carousel spreads the cards across the page but does not align left with the page content. Designers will need to review and make a decision.

allow 5 card carousel to spread over large screens

---

content/404.ts
pages/404.tsx

Cleans up the 404 page, removes the broken image and aligns the return home button with the rest of the website.

update 404 page

---

pages/see-more-resources.tsx

The two long URLs were breaking so that they did not create additional right side white space, but they were creating an undesired effect on mobile screens. To fix this, instead we use a title with the underlying URL linked.

update resource page copy

---

components/CustomButtons.tsx
styles/global.css

When clicking through the calculator on mobile devices, the page transitions were happening very quickly, and a finger still on the button when the page changed, was triggering an active hover state over the button in the same position on the page as the button pressed on the last page. In order to fix this, I have disabled hover on touch devices.

Mobile button hover

---

pages/calculator/[slug].tsx

On mobile screens the button on the Blake page was touching the footer. In order to avoid this situation I added a bottom margin of 36px to the outer calculator container on xs screens.

Fix blake button issue

---

components/layout/Footer.tsx

Adds LinkedIn and Facebook social media share buttons using SVG icons. Clicking the button links to the social media page with the share already pre-populated with `clearviction.org` which will include the opengraph metadata.

add facebook and linkedin share buttons to footer

---

pages/get-started/file-with-the-court.tsx

Removes the set width on the text block that was causing it to render at `312px` instead of the full width of the outer container.

remove set width from legal resources text block
